name: Basic code check

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements_dev.txt
      - run: echo "The workflow is now ready to lint your code on the runner."
      - name: Lint with flake8
        run: |
          flake8
      - run: echo "This job's status is ${{ job.status }}."

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements_dev.txt
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: Test with pytest
        run: |
          pytest --cov
      - run: echo "This job's status is ${{ job.status }}."

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install --upgrade build
      - run: echo "The workflow is now ready to build your code on the runner."
      - name: Build package
        run: |
          python -m build
      - run: echo "This job's status is ${{ job.status }}."
